tick_rate = 60

[ui]
use_nerd_font_icons = true
ui_scale = 100
show_help_bar = false
show_preview_panel = true
input_bar_position = "bottom"
theme = "catppuccin"

[previewers.file]
theme = "Catppuccin-Mocha"

[keybindings.Channel]
quit = "esc"
select_next_entry = ["down", "ctrl-n", "ctrl-j"]
select_prev_entry = ["up", "ctrl-p", "ctrl-k"]
select_next_page = "pagedown"
select_prev_page = "pageup"
scroll_preview_half_page_down = "ctrl-d"
scroll_preview_half_page_up = "ctrl-u"
select_entry = "enter"
copy_entry_to_clipboard = "ctrl-y"
toggle_remote_control = "ctrl-r"
toggle_send_to_channel = "ctrl-s"
toggle_help = "ctrl-g"
toggle_preview = "ctrl-o"

[keybindings.RemoteControl]
quit = "esc"
select_next_entry = ["down", "ctrl-n", "ctrl-j"]
select_prev_entry = ["up", "ctrl-p", "ctrl-k"]
select_next_page = "pagedown"
select_prev_page = "pageup"
select_entry = "enter"
toggle_remote_control = "ctrl-r"
toggle_help = "ctrl-g"
toggle_preview = "ctrl-o"

[keybindings.SendToChannel]
quit = "esc"
select_next_entry = ["down", "ctrl-n", "ctrl-j"]
select_prev_entry = ["up", "ctrl-p", "ctrl-k"]
select_next_page = "pagedown"
select_prev_page = "pageup"
select_entry = "enter"
toggle_send_to_channel = "ctrl-s"
toggle_help = "ctrl-g"
toggle_preview = "ctrl-o"

[shell_integration.commands]
"export" = "env"
"unset" = "env"

"cd" = "dirs"
"ls" = "dirs"
"rmdir" = "dirs"

"less" = "files"
"head" = "files"
"tail" = "files"
"bat" = "files"
"nvim" = "files"

"man" = "man"

"" = "history"

# image channel (Disabled while television doesn't support image previews)
# "chafa" = "image"
# "wallpaper" = "image"
