tick_rate = 60

[ui]
use_nerd_font_icons = true
ui_scale = 100
show_help_bar = false
show_preview_panel = true
input_bar_position = "bottom"
theme = "catppuccin"

[previewers.file]
theme = "Catppuccin-Mocha"

[keybindings]
quit = "esc"
select_next_entry = [ "down", "ctrl-n", ]
select_prev_entry = [ "up", "ctrl-p", ]
select_next_page = "pagedown"
select_prev_page = "pageup"
scroll_preview_half_page_down = "ctrl-d"
scroll_preview_half_page_up = "ctrl-u"
toggle_selection_down = "tab"
toggle_selection_up = "backtab"
confirm_selection = "enter"
copy_entry_to_clipboard = "ctrl-y"
toggle_remote_control = "ctrl-r"
toggle_send_to_channel = "ctrl-s"
toggle_help = "ctrl-g"
toggle_preview = "ctrl-o"

[shell_integration]
fallback_channel = "files"

[shell_integration.channel_triggers]
"files" = [ "less", "head", "tail", "bat", "nvim", ]
"dirs" = [ "cd", "ls", "rmdir", ]
"image" = [ "chafa", "wallpaper", ]
"man" = [ "man", "apropos", ]
"env" = [ "set", "unset", ]

[shell_integration.keybindings]
"smart_autocomplete" = "ctrl-a"
"command_history" = "ctrl-r"
