[[cable_channel]]
name = "files"
source_command = "fd -t f -H . $HOME"
preview_command = "bat -n --color=always {}"

[[cable_channel]]
name = "man"
source_command = "man -k . | cut -d ' ' -f 1"
preview_command = "man {}"

[[cable_channel]]
name = "dirs"
source_command = "fd -t d -H . $HOME"
preview_command = "lsd -Al1 {}"

[[cable_channel]]
name = "history"
source_command = "bat -n $HISTFILE | cut -d ';' -f 2-"

[[cable_channel]]
name = "image"
source_command = "fd -t f . $HOME | xargs file --mime-type | rg -F 'image/' | cut -d ':' -f 1"
preview_command = ":files:"

[[cable_channel]]
name = "remote-package-list"
source_command = "paru -Sl"
preview_command = "paru -Si {1}"

[[cable_channel]]
name = "local-package-list"
source_command = "paru -Q"
preview_command = "paru -Qi {0}"
