# Disabled keymaps
[[keymaps]]
command = "None" # Repeat
key_sequence = "C-r"
[[keymaps]]
command = "None" # ToggleFakeTrackRepeatMode
key_sequence = "M-r"
[[keymaps]]
command = "None" # Shuffle
key_sequence = "C-s"
[[keymaps]]
command = "None" # Mute
key_sequence = "_"
[[keymaps]]
command = "None" # Quit
key_sequence = "q"
[[keymaps]]
command = "None" # SelectNextOrScrollDown
key_sequence = "C-n"
[[keymaps]]
command = "None" # SelectNextOrScrollDown
key_sequence = "down"
[[keymaps]]
command = "None" #SelectPreviousOrScrollUp
key_sequence = "C-p"
[[keymaps]]
command = "None" #SelectPreviousOrScrollUp
key_sequence = "up"
[[keymaps]]
command = "None" #PageSelectNextOrScrollDown
key_sequence = "page_down"
[[keymaps]]
command = "None" #PageSelectPreviousOrScrollUp
key_sequence = "page_up"
[[keymaps]]
command = "None" #SelectFirstOrScrollToTop
key_sequence = "home"
[[keymaps]]
command = "None" #SelectLastOrScrolltoBottom
key_sequence = "end"
[[keymaps]]
command = "None" # ChooseSelected
key_sequence = "enter"
[[keymaps]]
command = "None" # RefreshPlayback
key_sequence = "r"
[[keymaps]]
command = "None" # RestartIntegratedClient
key_sequence = "R"
[[keymaps]]
command = "None" # ShowActionsOnSelectedItem
key_sequence = "C-space"
[[keymaps]]
command = "None" # AddSelectedItemToQueue
key_sequence = "Z"
[[keymaps]]
command = "None" # AddSelectedItemToQueue
key_sequence = "C-z"
[[keymaps]]
command = "None" # FocusNextWindow
key_sequence = "tab"
[[keymaps]]
command = "None" # FocusPreviousWindow
key_sequence = "backtab"
[[keymaps]]
command = "None" # BrowseUserPlaylists
key_sequence = "u p"
[[keymaps]]
command = "None" # BrowseUserFollowedArtists
key_sequence = "u a"
[[keymaps]]
command = "None" # BrowseUserSavedAlbums
key_sequence = "u A"
[[keymaps]]
command = "None" # CurrentlyPlayingContextPage
key_sequence = "g space"
[[keymaps]]
command = "None" # LyricsPage
key_sequence = "l"
[[keymaps]]
command = "None" # Queue
key_sequence = "z"
[[keymaps]]
command = "None" # OpenCommandHelp
key_sequence = "C-h"
[[keymaps]]
command = "None" # PreviousPage
key_sequence = "backspace"
[[keymaps]]
command = "None" # PreviousPage
key_sequence = "C-q"
[[keymaps]]
command = "None" # SortTrackByTitle
key_sequence = "s t"
[[keymaps]]
command = "None" # SortTrackByArtists
key_sequence = "s a"
[[keymaps]]
command = "None" # SortTrackByAlbum
key_sequence = "s A"
[[keymaps]]
command = "None" # SortTrackByAddedDate
key_sequence = "s D"
[[keymaps]]
command = "None" # SortTrackByDuration
key_sequence = "s d"
[[keymaps]]
command = "None" # ReverseOrder
key_sequence = "s r"
[[keymaps]]
command = "None" # MovePlaylistItemUp
key_sequence = "C-k"
[[keymaps]]
command = "None" # MovePlaylistItemDown
key_sequence = "C-j"

# Playback controls
[[keymaps]]
command = "ChooseSelected"
key_sequence = "o"
[[keymaps]]
command = "NextTrack"
key_sequence = "n"
[[keymaps]]
command = "PreviousTrack"
key_sequence = "p"
[[keymaps]]
command = "ResumePause"
key_sequence = "space"
[[keymaps]]
command = "PlayRandom"
key_sequence = "."
[[keymaps]]
command = "Repeat"
key_sequence = "r"
[[keymaps]]
command = "Shuffle"
key_sequence = "s"
[[keymaps]]
command = { VolumeChange = { offset = 5 }}
key_sequence = "="
[[keymaps]]
command = { VolumeChange = { offset = 5 }}
key_sequence = "-"
[[keymaps]]
command = "Mute"
key_sequence = "m"
[[keymaps]]
command = "SeekForward"
key_sequence = ">"
[[keymaps]]
command = "SeekBackward"
key_sequence = "<"
[[keymaps]]
command = "AddSelectedItemToQueue"
key_sequence = "q"

# Context movement
[[keymaps]]
command = "Quit"
key_sequence = "C-c"
[[keymaps]]
command = "ClosePopup"
key_sequence = "esc"
[[keymaps]]
command = "PreviousPage"
key_sequence = "u"
[[keymaps]]
command = "FocusPreviousWindow"
key_sequence = "h"
[[keymaps]]
command = "FocusNextWindow"
key_sequence = "l"
[[keymaps]]
command = "SelectNextOrScrollDown"
key_sequence = "j"
[[keymaps]]
command = "SelectPreviousOrScrollUp"
key_sequence = "k"
[[keymaps]]
command = "PageSelectNextOrScrollDown"
key_sequence = "C-f"
[[keymaps]]
command = "PageSelectPreviousOrScrollUp"
key_sequence = "C-b"
[[keymaps]]
command = "SelectFirstOrScrollToTop"
key_sequence = "g g"
[[keymaps]]
command = "SelectLastOrScrollToBottom"
key_sequence = "G"
[[keymaps]]
command = "MovePlaylistItemUp"
key_sequence = "K"
[[keymaps]]
command = "MovePlaylistItemDown"
key_sequence = "J"

# Goto context
[[keymaps]]
command = "JumpToCurrentTrackInContext"
key_sequence = "g c"
[[keymaps]]
command = "CurrentlyPlayingContextPage"
key_sequence = "g p"
[[keymaps]]
command = "TopTrackPage"
key_sequence = "g t"
[[keymaps]]
command = "RecentlyPlayedTrackPage"
key_sequence = "g r"
[[keymaps]]
command = "LikedTrackPage"
key_sequence = "g y"
[[keymaps]]
command = "LyricsPage"
key_sequence = "g L"
[[keymaps]]
command = "LibraryPage"
key_sequence = "g l"
[[keymaps]]
command = "SearchPage"
key_sequence = "g s"
[[keymaps]]
command = "BrowsePage"
key_sequence = "g b"
[[keymaps]]
command = "Queue"
key_sequence = "g q"

# Sort context
[[keymaps]]
command = "SortTrackByTitle"
key_sequence = "S t"
[[keymaps]]
command = "SortTrackByArtists"
key_sequence = "S a"
[[keymaps]]
command = "SortTrackByAlbum"
key_sequence = "S A"
[[keymaps]]
command = "SortTrackByAddedDate"
key_sequence = "S D"
[[keymaps]]
command = "SortTrackByDuration"
key_sequence = "S d"
[[keymaps]]
command = "ReverseTrackOrder"
key_sequence = "S r"

# Action menus
[[keymaps]]
command = "ShowActionsOnSelectedItem"
key_sequence = "g a"
[[keymaps]]
command = "ShowActionsOnCurrentTrack"
key_sequence = "a"

# Browse user lists
[[keymaps]]
command = "BrowseUserPlaylists"
key_sequence = "b p"
[[keymaps]]
command = "BrowseUserFollowedArtists"
key_sequence = "b f"
[[keymaps]]
command = "BrowseUserSavedAlbums"
key_sequence = "b a"

# Meta keymaps
[[keymaps]]
command = "SwitchTheme"
key_sequence = "T"
[[keymaps]]
command = "SwitchDevice"
key_sequence = "D"
[[keymaps]]
command = "Search"
key_sequence = "/"
[[keymaps]]
command = "CreatePlaylist"
key_sequence = "N"
[[keymaps]]
command = "OpenCommandHelp"
key_sequence = "?"
[[keymaps]]
command = "OpenCommandHelp"
key_sequence = "C-h"
[[keymaps]]
command = "OpenSpotifyLinkFromClipboard"
key_sequence = "O"
