#!/usr/bin/env bash

# Find file in .config to open in Neovim
nf() {
    FZF_DEFAULT_COMMAND="fd --type file --hidden --exclude .git --exclude .old --exclude zsh/plugins --base-directory ${XDG_CONFIG_HOME}"
    FZF_ARGS=(
        --multi
        --preview="cat --number ${XDG_CONFIG_HOME}/{}"
        --bind "enter:become(nvim ${XDG_CONFIG_HOME}/{})"
    )

    FZF_DEFAULT_COMMAND="${FZF_DEFAULT_COMMAND}" fzf "${FZF_ARGS[@]}"
}

# Find repositories
gf() {
    REPO_DIR="${HOME}/Desktop/Repositories"
    FZF_DEFAULT_COMMAND="fd --type directory --exact-depth 3 --base-directory ${REPO_DIR}"
    FZF_ARGS=(
        --preview="eza --tree --color=always --icons=always ${REPO_DIR}/{}"
    )

    CD_PATH="$(FZF_DEFAULT_COMMAND="${FZF_DEFAULT_COMMAND}" fzf "${FZF_ARGS[@]}")" || exit 0
    cd "${REPO_DIR}"/"${CD_PATH}" || return
}
