[general]
fullscreen = false
early-exit = true
initial-tool = "brush"
copy-command = "wl-copy"
annotation-size-factor = 2
output-filename = "/tmp/test-%Y-%m-%d_%H:%M:%S.png"
default-hide-toolbars = false
primary-highlighter = "block"
disable-notifications = true

[font]
family = "AdwaitaMono Bold"

[color-palette]
palette = [
    "#00ffff",
    "#a52a2a",
    "#dc143c",
    "#ff1493",
    "#ffd700",
    "#008000",
]
