#!/usr/bin/env bash

OPTIONS=(
    poweroff
    reboot
    lock
)

SELECTED=$(for OPTION in "${OPTIONS[@]}"; do echo "${OPTION}"; done | anyrun --plugins libstdin.so)

case "${SELECTED}" in
    poweroff)
        systemctl poweroff
        ;;
    reboot)
        systemctl reboot
        ;;
    lock)
        hyprlock
        ;;
    *)
        return 0
        ;;
esac
