#!/usr/bin/env bash
# shellcheck disable=SC2016
# vim: filetype=bash

# Script mostly taken from this example
# https://wiki.hyprland.org/Hypr-Ecosystem/hyprpaper/#using-this-keyword-to-randomize-your-wallpaper

WALLPAPER_DIR="${HOME}/Pictures/Wallpapers"

# TODO: Fix preview, currently doesn't erase previous images from window.
FZF_ARGS=(
    --preview-window="right:70%"
    --preview='
        dim=${FZF_PREVIEW_COLUMNS}x${FZF_PREVIEW_LINES}
        chafa -f kitty -s ${dim} {}
    '
)

case "${1}" in
    random)
        WALLPAPER=$(fd -t f . "${WALLPAPER_DIR}" | shuf -n 1)
        ;;
    pick)
        # Open wallpaper selector in fzf
        WALLPAPER=$(fd -t f . "${WALLPAPER_DIR}" | fzf "${FZF_ARGS[@]}")
        ;;
    *)
        # Pick selected wallpaper
        WALLPAPER="$1"
        ;;
esac

ACCEPTED_MIMETYPE="image/*"
MIMETYPE="$(xdg-mime query filetype "${WALLPAPER}")"

if [[ -n "${WALLPAPER}" ]] && [[ "${MIMETYPE}" =~ ${ACCEPTED_MIMETYPE} ]]; then
    ln -sf "${WALLPAPER}" "${HOME}"/.background
    systemctl --user restart swaybg.service
    exit 0
fi

exit 1
