#!/usr/bin/env bash

case "$1" in
    random)
        WALLPAPER="$(fd -t f . "$HOME"/Pictures/Wallpapers | shuf -n 1)"
        ;;
    pick)
        # TODO: Fix preview
        WALLPAPER="$(fd -t f . "$HOME"/Pictures/Wallpapers | fzf --preview 'xargs -ro chafa')"
        ;;
    *)
        WALLPAPER="$1"
        ;;
esac

if [[ -n "$WALLPAPER" ]]; then
    ln -f "$WALLPAPER" "$HOME"/.background # Update hyprlock background to new wallpaper
    swww img "$HOME/.background"           # Set new wallpaper
fi
