#!/usr/bin/env bash
# shellcheck disable=SC2016
# vim: filetype=bash

# Script mostly taken from this example
# https://wiki.hyprland.org/Hypr-Ecosystem/hyprpaper/#using-this-keyword-to-randomize-your-wallpaper

WALLPAPER_DIR="${HOME}/Pictures/Wallpapers"
FZF_ARGS=(
    --preview='
        dim=${FZF_PREVIEW_COLUMNS}x${FZF_PREVIEW_LINES}
        chafa -f kitty -s ${dim} {}
    '
)

case "${1}" in
    random)
        WALLPAPER=$(fd -t f . "${WALLPAPER_DIR}" | shuf -n 1)
        ;;
    pick)
        # TODO: Fix preview
        # Open wallpaper selector in fzf
        WALLPAPER=$(fd -t f . "${WALLPAPER_DIR}" | fzf "${FZF_ARGS[@]}")
        ;;
    *)
        # Pick selected wallpaper
        WALLPAPER="$1"
        ;;
esac

if [[ -n "${WALLPAPER}" ]]; then
    # Hardlink wallpaper to $HOME (used by hyprlock)
    ln -f "${WALLPAPER}" "${HOME}"/.background
    systemctl --user restart swaybg.service
fi
