classic: false
blocks:
  - permission
  - user
  - group
  - size
  - date
  - name
color:
  when: always
  theme: custom
date: relative
dereference: false
icons:
  when: always
  theme: fancy
  separator: " "
indicators: false
layout: oneline
recursion:
  enabled: false
size: default
permission: octal
sorting:
  column: name
  reverse: false
  dir-grouping: none
no-symlink: false
total-size: true
hyperlink: never
symlink-arrow: ⇒
header: false
literal: false
truncate-owner:
  after:
  marker: ""
